
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expose-cr
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["deployments", "services", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
