apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pdfdocuments.example.com.my.domain
spec:
  group: example.com.my.domain 
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                documentName:
                  type: string
                text:
                  type: string
  scope: Namespaced
  names:
    plural: pdfdocuments
    singular: pdfdocument
    kind: PdfDocument
    shortNames:
      - pdf
      - pdfs
